### ISSUE TITLE
Support for more than 99 hours

### ISSUE THREAD

**Issue by 3lvis** [jhthorsen/timer#7]
I would like to be able to have more than 99 hours in my timer

**Comment by arne** [comment]
Is this really useful?

If support for more than 99 hours is needed, days would probably be a better unit.

**Comment by 3lvis** [comment]
That would be even better! I was using it for a countdown for an event that I have.

**Comment by 3lvis** [comment]
Doing some spring cleaning, please open a new issue if you still want to do this.

**Comment by jhthorsen** [comment]
Enjoy! 😄 

https://jhthorsen.github.com/timer
